package explain

import (
	"fmt"
	"html"
	"math/rand"
	"regexp"
	"strings"
)

// Render turns a Spec into one self-contained HTML page: no external CSS, no
// external JavaScript, no fonts to fetch, so the file can be mailed, committed
// as a review artifact, or opened from a network share.
//
// This is the piece the explain-diff skill gets from render.py. Keeping the
// boilerplate here rather than in the prompts is the whole point: every
// invocation writes content, never markup scaffolding, so the page does not
// drift between runs and the model never spends tokens on a <style> tag.
//
// The model-authored HTML in the sections is passed through as markup (it is
// the vocabulary the prompt defines, and the renderer's CSS styles it), after
// sanitizeHTML. Everything else — titles, headings, questions, options and
// their feedback — is escaped.
func Render(spec Spec) (string, error) {
	spec.Normalize()
	if len(spec.Sections) == 0 && len(spec.Quiz) == 0 {
		return "", fmt.Errorf("nothing to render: the spec has no sections and no quiz")
	}

	var b strings.Builder
	b.WriteString("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n")
	b.WriteString("<meta charset=\"UTF-8\">\n")
	b.WriteString("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n")
	b.WriteString("<title>" + esc(spec.Title) + "</title>\n")
	b.WriteString("<style>\n" + pageCSS + "</style>\n</head>\n<body>\n\n")

	b.WriteString("<h1>" + esc(spec.Title) + "</h1>\n")
	if spec.Subtitle != "" {
		b.WriteString(`<p class="subtitle">` + esc(spec.Subtitle) + "</p>\n")
	}
	b.WriteString(renderTOC(spec))
	b.WriteString("\n")

	for _, s := range spec.Sections {
		b.WriteString(`<h2 id="` + esc(s.ID) + `">` + esc(s.Heading) + "</h2>\n")
		b.WriteString(strings.TrimSpace(s.HTML))
		b.WriteString("\n\n")
	}

	if len(spec.Quiz) > 0 {
		b.WriteString(`<h2 id="quiz">Quiz</h2>` + "\n")
		b.WriteString(`<p class="score" id="quiz-score"></p>` + "\n")
		for _, q := range spec.Quiz {
			b.WriteString(renderQuestion(q))
		}
	}

	b.WriteString(`<p class="footer">Generated by pr-review-agent from the change itself. ` +
		`Every claim on this page came from the model reading the diff; check it against the code.</p>` + "\n")
	b.WriteString("\n<script>\n" + quizJS + "</script>\n</body>\n</html>\n")
	return b.String(), nil
}

// renderTOC lists the sections, and the quiz when there is one.
func renderTOC(spec Spec) string {
	var b strings.Builder
	b.WriteString(`<div class="toc"><strong>Contents</strong><ul>` + "\n")
	for _, s := range spec.Sections {
		b.WriteString(`  <li><a href="#` + esc(s.ID) + `">` + esc(s.Heading) + "</a></li>\n")
	}
	if len(spec.Quiz) > 0 {
		b.WriteString(`  <li><a href="#quiz">Quiz</a></li>` + "\n")
	}
	b.WriteString("</ul></div>\n")
	return b.String()
}

// renderQuestion writes one quiz item. Option order is shuffled at render
// time, so the correct answer is not always in the same place from page to
// page, and every option carries its own feedback for when it is clicked.
func renderQuestion(q Question) string {
	order := make([]int, len(q.Options))
	for i := range order {
		order[i] = i
	}
	rand.Shuffle(len(order), func(i, j int) { order[i], order[j] = order[j], order[i] })

	var b strings.Builder
	b.WriteString(`<div class="quiz-q">` + "\n")
	b.WriteString(`<p class="q-text">` + esc(q.Question) + "</p>\n")
	for _, i := range order {
		o := q.Options[i]
		fmt.Fprintf(&b, `<button class="quiz-opt" data-correct="%t" data-feedback="%s">%s</button>`+"\n",
			o.Correct, attr(o.Feedback), esc(o.Text))
	}
	b.WriteString("</div>\n\n")
	return b.String()
}

// renderableText is a rough plaintext size of the whole spec, for logs.
func renderableText(spec Spec) string {
	var b strings.Builder
	for _, s := range spec.Sections {
		b.WriteString(s.HTML)
	}
	for _, q := range spec.Quiz {
		b.WriteString(q.Question)
		for _, o := range q.Options {
			b.WriteString(o.Text)
			b.WriteString(o.Feedback)
		}
	}
	return b.String()
}

func esc(s string) string { return html.EscapeString(s) }

// attr escapes a value for a double-quoted HTML attribute.
func attr(s string) string { return html.EscapeString(s) }

// dangerous tags and inline event handlers are stripped from model-authored
// HTML. The model is writing prose, not code: a <script> or an onclick in a
// diff that happened to contain one is a bug, not a feature — and these pages
// get shared.
// scriptishTags are the elements stripped from model-authored markup: they
// either execute, load remote content, or redefine the page.
var scriptishTags = []string{"script", "style", "iframe", "object", "embed", "link", "meta"}

// tagRe matches one HTML tag and captures its name; scriptishBlock matches a
// whole dangerous element including its contents, since <script>alert(1)</script>
// has to go as a unit rather than leaving the payload behind as text. Go's
// regexp has no backreferences, so scriptishBlock is built per tag name.
var (
	tagRe           = regexp.MustCompile(`(?is)<\s*/?\s*([a-z][a-z0-9]*)\b[^>]*>`)
	eventAttr       = regexp.MustCompile(`(?is)\s+on[a-z]+\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)`)
	scriptishBlocks = map[string]*regexp.Regexp{}
)

func init() {
	for _, tag := range scriptishTags {
		// A container element: drop it and everything inside it.
		scriptishBlocks[tag] = regexp.MustCompile(
			`(?is)<\s*` + tag + `\b[^>]*>.*?<\s*/\s*` + tag + `\s*>`)
		// The same tag used self-closing or without a close tag (which is
		// what a truncated model reply leaves behind).
		scriptishBlocks[tag+"!"] = regexp.MustCompile(`(?is)<\s*` + tag + `\b[^>]*/?\s*>`)
	}
}

func isScriptish(tag string) bool {
	for _, t := range scriptishTags {
		if strings.EqualFold(tag, t) {
			return true
		}
	}
	return false
}

// sanitizeHTML removes script-like elements and inline event handlers from
// model-authored markup. It is defense in depth, not a sanitizer: the output
// is a page written by a model reading a diff in a repository the user
// already trusts, and the vocabulary the prompt allows is a short list of
// formatting tags. What it does guarantee is that a diff containing a script
// tag or an onerror attribute — a test fixture, a doc example — cannot turn
// the explanation into an active page when someone opens it.
func sanitizeHTML(s string) string {
	// Whole elements first, contents included, so no payload survives as
	// orphaned text; then any stray open/close tag; then attributes.
	for _, tag := range scriptishTags {
		s = scriptishBlocks[tag].ReplaceAllString(s, "")
		s = scriptishBlocks[tag+"!"].ReplaceAllString(s, "")
	}
	s = tagRe.ReplaceAllStringFunc(s, func(m string) string {
		if mm := tagRe.FindStringSubmatch(m); mm != nil && isScriptish(mm[1]) {
			return ""
		}
		return m
	})
	return eventAttr.ReplaceAllString(s, "")
}
